### ISSUE TITLE
Is it only english and japanese translation repository?

### ISSUE THREAD

**Issue by Blueberryy** [Giratena/Succubus-Senki-Translation-Project#166]
Can other language translations be added by random translators from internet and how do we do that?

**Comment by OfficialLayton** [comment]
Hi Blueberryy!

Sorry for the late response.

Yes you could certainly edit these translation files over with another language and theoretically ask the dev to import them into the game as another translation.

They are quite open to more languages so I think it would be possible.

**Comment by Blueberryy** [comment]
> Hi Blueberryy!
> 
> Sorry for the late response.
> 
> Yes you could certainly edit these translation files over with another language and theoretically ask the dev to import them into the game as another translation.
> 
> They are quite open to more languages so I think it would be possible.

Thanks! I would make russian translation soon
